let pizzaJson = [
    {id:1, name:'Mussarela', img:'images/pizza.png', price:[20.19, 25.30, 55.30], sizes:['320g', '530g', '860g'], description:'Nossa pizza de mussarela é preparada com uma generosa camada de queijo mussarela derretido, coberta com um toque especial de orégano e um fio de azeite. Assada em forno à lenha, ela tem bordas douradas e crocantes, com um sabor suave e irresistível que agrada a todos os paladares. Ideal para quem valoriza o sabor simples e autêntico de uma boa pizza. '},
    {id:2, name:'Calabresa', img:'images/pizza2.png', price:[18.00, 22.00, 36.50],sizes:['320g', '530g', '860g'], description:'Nossa pizza de calabresa é feita com fatias generosas de linguiça calabresa levemente apimentada, sobre uma base de molho de tomate artesanal e queijo mussarela derretido. Finalizada com rodelas de cebola, orégano e um leve fio de azeite, ela combina crocância e intensidade em cada pedaço. Perfeita para quem curte uma pizza marcante e cheia de personalidade! '},
    {id:3, name:'Quatro Queijos', img:'images/pizza3.png', price:[17.45, 20.45, 40.50],  sizes:['320g', '530g', '860g'], description:'Nossa pizza quatro queijos une a cremosidade da mussarela, o sabor marcante do gorgonzola, a delicadeza do catupiry e a intensidade do parmesão ralado na hora. Tudo isso sobre uma base de molho branco ou de tomate e uma massa leve e crocante, assada até atingir o ponto perfeito de gratinação. Uma experiência rica e sofisticada em cada mordida! '},
    {id:4, name:'Americana', img:'images/pizza4.png', price:[19.77, 25.50, 50.25], sizes:['320g', '530g', '860g'], description:'Nossa pizza americana é perfeita para quem curte uma refeição robusta e cheia de sabor! Ela leva mussarela derretida, fatias generosas de presunto, bacon crocante, calabresa e rodelas de ovo cozido, tudo sobre um molho de tomate temperado com ervas. Finalizada com orégano e um toque especial de cheddar ou catupiry, essa pizza é um verdadeiro clássico que agrada em cheio quem gosta de combinações marcantes e bem recheadas! '},
    {id:5, name:'Sorvete', img:'images/pizza5.png', price:[21.43, 27.00, 56.50], sizes:['320g', '530g', '860g'], description:'Nossa pizza de sorvete é feita com uma base leve e crocante, coberta com uma generosa camada de sorvete cremoso — sabores à sua escolha, como chocolate, morango, baunilha ou napolitano. Para deixar ainda mais irresistível, adicionamos calda de chocolate, granulados, frutas frescas, confeitos coloridos ou pedaços de brownie. Uma explosão de doçura e diversão a cada fatia! '},
    {id:6, name:'Moda da Casa', img:'images/pizza6.png', price:[18.55, 22.50, 38.50], sizes:['320g', '530g', '860g'], description:'A Pizza Moda da Casa combina os ingredientes mais pedidos com um toque de criatividade: uma base generosa de mussarela, fatias de calabresa artesanal, presunto suculento, bacon crocante, cebola roxa levemente dourada, azeitonas pretas e um toque especial de catupiry. Finalizada com orégano e um fio de azeite, essa pizza é a escolha perfeita para quem quer saborear o melhor da casa em uma única fatia!  '},
    {id:7, name:'Chocolate', img:'images/pizza7.png', price:[22.36, 27.50, 60.00], sizes:['320g', '530g', '860g'], description:'Nossa pizza de chocolate é feita com uma base leve e macia, coberta com uma generosa camada de chocolate ao leite derretido, que se espalha até as bordas. Para deixar ainda mais especial, adicionamos confeitos coloridos, morangos frescos, raspas de chocolate ou marshmallows — você escolhe os complementos! Servida quentinha, é a pedida ideal para adoçar qualquer momento com muito sabor e carinho.  '},
    {id:8, name:'Frango com Catupiry', img:'images/pizza8.png', price:[20.99, 26.00, 55.50], sizes:['320g', '530g', '860g'], description:'Nossa pizza de frango com catupiry é feita com uma base leve e crocante, coberta com um molho de tomate temperado, pedaços suculentos de peito de frango desfiado, cebola roxa caramelizada e uma generosa camada de catupiry cremoso. Finalizada com orégano e um toque especial de azeitonas verdes ou pretas, essa pizza é perfeita para quem ama sabores caseiros e aconchegantes!  '},
    {id:9, name:'Palmito', img:'images/pizza9.png', price:[19.99, 25.50, 50.25], sizes:['320g', '530g', '860g'], description:'Nossa pizza de palmito é feita com uma base leve e crocante, coberta com um molho de tomate temperado, fatias generosas de palmito pupunha, cebola roxa caramelizada e uma camada de queijo mussarela derretido. Finalizada com orégano e um toque especial de azeitonas verdes ou pretas, essa pizza é perfeita para quem ama sabores frescos e leves! '},
    {id:10, name:'Vegetariana', img:'images/pizza10.png', price:[20.00, 25.30, 55.30], sizes:['320g', '530g', '860g'], description:'Nossa pizza vegetariana é feita com uma base leve e crocante, coberta com um molho de tomate temperado, queijo mussarela derretido e uma seleção de legumes frescos como abobrinha, berinjela, pimentão colorido e cebola roxa. Finalizada com orégano e um toque especial de azeitonas verdes ou pretas, essa pizza é perfeita para quem ama sabores leves e saudáveis! '}
];